version: '3.3'
services:

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: nginx
    container_name: nginx
    depends_on:
      - client
    ports:
      - "80:80"

  client:
    build:
      dockerfile: Dockerfile
      context: client/
    container_name: client

  backend:
    build: 
      dockerfile: Dockerfile
      context: backend/
    container_name: backend
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data


  