version: '3.3'
services:

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: nginx

  client:
    build:
      dockerfile: Dockerfile.dev
      context: client/
    volumes:
      - /app/node_modules
      - ./client:/app

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: backend/
    volumes:
      - /app/node_modules
      - ./backend:/app    


  